name: Super.Human.Portal Prod

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16 ]
    steps:

    - name: Checkout Super.Human.Portal
      uses: actions/checkout@v3.3.0
      with:
        path: './SuperHumanPortal'

    - name: Checkout PureMVC
      uses: actions/checkout@v3.3.0 
      with:
        repository: 'PureMVC/puremvc-as3-multicore-framework'
        path: './puremvc-as3-multicore-framework'

    - name: Set up JDK 
      uses: actions/setup-java@v3.9.0
      with:
          distribution: adopt
          java-version: ${{ matrix.java }}

    - name: Build Super.Human.Portal
      run: mvn -s SuperHumanPortal/Super.Human.Portal_Royale/settings.xml clean package --file SuperHumanPortal/Super.Human.Portal_Royale/pom.xml

    - name: Read version
      id: readversion
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
        xml-file: SuperHumanPortal/Super.Human.Portal_Royale/target/classes/version.xml
        xpath: '/root/version'

    - name: Zip artifact for deployment
      run: zip Super.Human.Portal.zip SuperHumanPortal/Super.Human.Portal_Royale/target/javascript/bin/js-release/* -r

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: Production Release
        tag_name: ${{ steps.readversion.outputs.info }}
        body: |
          This is a Production Release of Super.Human.Portal.
        draft: true
        prerelease: false
        files: |
          Super.Human.Portal.zip          
        fail_on_unmatched_files: true
